# Generated by Django 4.0.3 on 2022-05-29 20:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='unique_id',
            new_name='id_user',
        ),
    ]
