# Generated by Django 3.2.13 on 2022-07-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_image',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_image', models.FileField(upload_to='property_images')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.property')),
            ],
        ),
    ]
