# Generated by Django 4.0.3 on 2022-07-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image',
            field=models.FileField(upload_to='property_images'),
        ),
    ]
