# Generated by Django 4.0.3 on 2022-07-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_property_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, default='Untitled274_20220622164957-removebg-preview.png', null=True, upload_to='agents profile image'),
        ),
    ]
