# Generated by Django 4.0.4 on 2022-07-21 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220718_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='header_image',
            field=models.ImageField(upload_to='property_header_images'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property_image',
            field=models.ImageField(upload_to='property_images'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(default=None, max_length=50)),
                ('start_date', models.DateField(default=None)),
                ('time', models.CharField(default=None, max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.property')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
