# Generated by Django 3.2.13 on 2022-06-09 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_unique_id_userprofile_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
