# Generated by Django 4.0.3 on 2022-04-02 22:26

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_profile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('agent', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='property_images')),
                ('description', models.TextField()),
                ('built_on', models.DateTimeField(default=datetime.date)),
                ('listed_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
