# Generated by Django 4.0.3 on 2022-07-06 12:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_unique_id_userprofile_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.AddField(
            model_name='property',
            name='cctv',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='drain',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='power',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='solar_power',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='temp',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AddField(
            model_name='property',
            name='water',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
    ]
