# Generated by Django 4.0.3 on 2022-07-06 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_property_features_property_cctv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='images',
            new_name='header_image',
        ),
    ]
