# Generated by Django 4.0.3 on 2022-05-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_coverpic_alter_property_home_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='listed_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_id',
            field=models.FileField(blank=True, null=True, upload_to='business ids'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='coverpic',
            field=models.ImageField(blank=True, null=True, upload_to='agents cover image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gov_id',
            field=models.FileField(blank=True, null=True, upload_to='government ids'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='in_business_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='agents profile image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='utility_bills',
            field=models.FileField(blank=True, null=True, upload_to='utility bills'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
