# Generated by Django 4.0.4 on 2022-09-10 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(choices=[('Abuja', 'Abuja'), ('Lagos', 'Lagos'), ('Osun', 'Osun'), ('Ibadan', 'Ibadan')], max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.upload_agent_image),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SavedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to='main.property')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saved_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
