# Generated by Django 4.0.3 on 2022-04-02 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
