# Generated by Django 4.0.3 on 2022-07-06 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_images_property_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='list_type',
            field=models.CharField(choices=[('For sale', 'For Sale'), ('For rent', 'For Rent')], max_length=25),
        ),
    ]
