# Generated by Django 4.0.3 on 2022-07-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_property_property_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='coverpic',
        ),
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.FileField(default=None, upload_to='property_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='property_list',
            field=models.ManyToManyField(blank=True, related_name='property_list', to='main.property'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='agents profile image'),
        ),
        migrations.DeleteModel(
            name='Property_image',
        ),
    ]
