# Generated by Django 4.0.3 on 2022-04-03 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_property_built_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='home_type',
            field=models.CharField(choices=[('BG', 'Bungalow'), ('DP', 'Duplex'), ('AP', 'Apartment'), ('MN', 'Mansion'), ('VA', 'Villa'), ('CO', 'Condo')], default='AP', max_length=2),
        ),
        migrations.AddField(
            model_name='property',
            name='list_type',
            field=models.CharField(choices=[('FS', 'For Sale'), ('FR', 'For Rent')], default='FS', max_length=2),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='open_house',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='property',
            name='property_link',
            field=models.CharField(max_length=500, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='property',
            name='property_location',
            field=models.CharField(default='location', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='property_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='built_on',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
