# Generated by Django 4.0.4 on 2022-07-25 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='property_list',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.property'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(editable=False, max_length=250),
        ),
    ]
