# Generated by Django 4.0.3 on 2022-07-07 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_property_property_id_alter_property_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='list_type',
            field=models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=25),
        ),
    ]
