# Generated by Django 4.0.3 on 2022-04-03 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_property_agent_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_on',
            field=models.DateField(default=datetime.date.fromtimestamp),
        ),
    ]
