# Generated by Django 4.0.4 on 2022-07-29 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userprofile_property_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property_agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL),
        ),
    ]
