# Generated by Django 4.0.3 on 2022-07-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userprofile_coverpic_property_property_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='main.review'),
        ),
    ]
