# Generated by Django 4.0.3 on 2022-04-03 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_property_built_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_on',
            field=models.DateField(default=datetime.date(2022, 4, 3)),
        ),
    ]
