# Generated by Django 4.0.3 on 2022-07-16 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='listing_agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
