# Generated by Django 3.2.13 on 2022-07-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_content_review_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='property',
            new_name='listing',
        ),
    ]
