# Generated by Django 4.0.4 on 2022-08-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_property_agent_chat'),
    ]

    operations = [
    ]
