# Generated by Django 4.0.3 on 2022-05-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userprofile_id_userprofile_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_user',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
