# Generated by Django 4.0.3 on 2022-04-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_property_built_on_alter_property_listed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listed_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='open_house',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
