# Generated by Django 4.0.3 on 2022-04-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_property_built_on_alter_property_listed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='open_house',
            field=models.DateField(auto_now=True),
        ),
    ]
