# Generated by Django 4.0.4 on 2022-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_review_user_booking_property_agent_and_more'),
    ]

    operations = [
        # create review model
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, null=True, max_length=500)),
                ('rating', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Fair', 'Fair'), ('Bad', 'Bad')], default='Fair', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=False, auto_now=True)),
                ('property', models.ForeignKey(to='main.Property', related_name='reviews', default=None, on_delete=models.CASCADE)),
                ('user', models.ForeignKey(to='main.Userprofile', related_name='reviews', default=None, on_delete=models.CASCADE)),
            ],
        ),
    ]
