# Generated by Django 4.0.3 on 2022-04-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_property_open_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listed_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='open_house',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_link',
            field=models.URLField(max_length=500, null=b'I01\n'),
        ),
    ]
