# Generated by Django 4.0.3 on 2022-05-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_property_property_views_alter_property_images_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
