# Generated by Django 4.0.3 on 2022-04-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_property_built_on_alter_property_listed_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='listed_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
