# Generated by Django 4.0.4 on 2022-08-21 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_booking_property_agent_alter_chat_message_and_more'),
    ]

    operations = [
    ]
