# Generated by Django 4.0.3 on 2022-05-20 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_userprofile_id_user_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
