# Generated by Django 4.0.3 on 2022-04-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_property_open_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_on',
            field=models.DateTimeField(null=True),
        ),
    ]
