# Generated by Django 4.0.3 on 2022-05-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile_unique_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
