# Generated by Django 4.0.3 on 2022-05-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_property', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.CharField(choices=[(1, 'Bad'), (2, 'Fair'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=1, max_length=200)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.property')),
            ],
        ),
    ]
