# Generated by Django 4.0.3 on 2022-04-10 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_property_built_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='bathrooms',
            new_name='full_bathrooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_price',
            new_name='garage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='open_house',
        ),
        migrations.AddField(
            model_name='property',
            name='half_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='one_quarter_bathrooms',
            field=models.IntegerField(default=0),
        
        ),
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(default='property name', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='three_quarter_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='property',
            name='home_type',
            field=models.CharField(choices=[('SH', 'Single-family'), ('SD', 'Semi-detached'), ('AP', 'Apartment'), ('TH', 'Townhomes'), ('MF', 'Multi-family'), ('MH', 'Mobile/Manufactured'), ('CO', 'Condo')], default='Single-family', max_length=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_link',
            field=models.URLField(blank=True, max_length=500, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_location',
            field=models.CharField(default='property location', max_length=500),
        ),
    ]
