# Generated by Django 4.0.3 on 2022-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_property_saved_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
