# Generated by Django 4.0.3 on 2022-04-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_bathrooms_property_full_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='home_type',
            field=models.CharField(choices=[('SH', 'Single-family'), ('SD', 'Semi-detached'), ('AP', 'Apartment'), ('TH', 'Townhomes'), ('MF', 'Multi-family'), ('MH', 'Mobile/Manufactured'), ('CO', 'Condo')], default='Single-family', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='list_type',
            field=models.CharField(choices=[('FS', 'For Sale'), ('FR', 'For Rent')], default='For Sale', max_length=25),
        ),
    ]
