# Generated by Django 4.0.3 on 2022-04-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_property_property_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
