# Generated by Django 4.0.3 on 2022-04-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_property_remove_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='list_type',
            field=models.CharField(choices=[('FS', 'For Sale'), ('FR', 'For Rent')], default='FS', max_length=25),
        ),
    ]
