# Generated by Django 4.0.3 on 2022-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_property_property_city_property_property_tel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='dishwater',
        ),
        migrations.AddField(
            model_name='property',
            name='dishwasher',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='air_con',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='attic',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='basement',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='bball',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='bbq_area',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='chandelier',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='closets',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='dining_room',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='dryer',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='equiped_kitchen',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='fence',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='fireplace',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='fitness_arena',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='freezer_fridge',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='garbage_disposer',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='garden',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='gate',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='indoor_pool',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='laundry_room',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='library',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='office',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='oven',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='patio',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='pool',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='porch',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='security',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='smoke_detector',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='solar_power',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='spa',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='sport_arena',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='sprinkler',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='tennis_court',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='washing_machine',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='wifi',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
        migrations.AlterField(
            model_name='property',
            name='workshop',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=25),
        ),
    ]
