# Generated by Django 4.0.3 on 2022-04-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_property_dishwater_property_dishwasher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_tel',
            field=models.BigIntegerField(default=0),
        ),
    ]
