# Generated by Django 4.0.3 on 2022-04-25 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_property_property_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_name', models.CharField(max_length=250)),
                ('agency_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('agency_bio', models.CharField(max_length=700)),
                ('agency_displayname', models.CharField(max_length=150)),
                ('agency_tel', models.IntegerField(default=0)),
                ('agency_profilepic', models.ImageField(upload_to='agency profile image')),
                ('agency_email', models.EmailField(max_length=254)),
                ('agency_website', models.URLField()),
                ('agency_address', models.CharField(max_length=500)),
                ('agency_rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('agency_whatsapp', models.IntegerField()),
                ('agency_facebook', models.URLField()),
                ('agency_instagram', models.URLField()),
                ('agency_twitter', models.URLField()),
                ('agency_linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_name', models.CharField(max_length=250)),
                ('agent_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('in_business_since', models.DateTimeField(null=True)),
                ('agent_bio', models.CharField(max_length=700)),
                ('agent_displayname', models.CharField(max_length=150)),
                ('agent_tel', models.IntegerField(default=0)),
                ('agent_profilepic', models.ImageField(upload_to='agent profile image')),
                ('agent_email', models.EmailField(max_length=254)),
                ('agent_website', models.URLField()),
                ('agent_license', models.CharField(max_length=700)),
                ('agent_address', models.CharField(max_length=500)),
                ('agent_rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('agent_whatsapp', models.IntegerField()),
                ('agent_facebook', models.URLField()),
                ('agent_instagram', models.URLField()),
                ('agent_twitter', models.URLField()),
                ('agent_linkedin', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id_user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tel',
            field=models.IntegerField(default=0),
        ),
    ]
