# Generated by Django 4.0.3 on 2022-04-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_property_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
    ]
