# Generated by Django 4.0.3 on 2022-04-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_delete_agent_userprofile_email_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
