# Generated by Django 4.0.3 on 2022-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=models.EmailField(default='fakeemail@fake.com', max_length=254, unique=True), max_length=50),
        ),
    ]
