# Generated by Django 4.0.3 on 2022-04-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=models.EmailField(default='fakeemail@fake.com', max_length=254, unique=True), max_length=50),
        ),
    ]
