# Generated by Django 4.0.3 on 2022-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_userprofile_password_alter_userprofile_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
