# Generated by Django 4.0.3 on 2022-04-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_userprofile_id_userprofile_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
