# Generated by Django 4.0.3 on 2022-04-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_userprofile_id_user_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tel',
        ),
    ]
